# Generated by Django 5.0 on 2023-12-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0004_remove_album_artistas_remove_artista_generos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'permissions': [('ver_albumes', 'Ver albumes'), ('crear_albumes', 'Crear albumes'), ('editar_albumes', 'Editar albumes'), ('eliminar_albumes', 'Eliminar albumes'), ('crear_album_propio', 'Crear album propio'), ('editar_album_propio', 'Editar album propio'), ('eliminar_album_propio', 'Eliminar album propio')], 'verbose_name': 'Album', 'verbose_name_plural': 'Albumes'},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'permissions': [('ver_artistas', 'Ver artistas'), ('crear_artistas', 'Crear artistas'), ('editar_artistas', 'Editar artistas'), ('eliminar_artistas', 'Eliminar artistas')], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'permissions': [('ver_canciones', 'Ver canciones'), ('crear_canciones', 'Crear canciones'), ('editar_canciones', 'Editar canciones'), ('eliminar_canciones', 'Eliminar canciones'), ('crear_cancion_propia', 'Crear canción propia'), ('editar_cancion_propia', 'Editar canción propia'), ('eliminar_cancion_propia', 'Eliminar canción propia')], 'verbose_name': 'Canción', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'permissions': [('ver_generos', 'Ver géneros'), ('crear_generos', 'Crear géneros'), ('editar_generos', 'Editar géneros'), ('eliminar_generos', 'Eliminar géneros')], 'verbose_name': 'Género', 'verbose_name_plural': 'Generos'},
        ),
        migrations.RemoveField(
            model_name='genero',
            name='logo',
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='music_library.genero'),
        ),
    ]
